version: '3.7'
services:
  dls:
    container_name: deep-learning-studio
    image: docker.io/deepcognitionlabs/deep-learning-studio:latest
    restart: always
    environment:
      - DLS_EULA_AGREED=y
    ports:
      - '8888:8888' 
      - '8880:8880'
      - '8881:80'
      - '3000:3000'
    volumes:
      - ./dls/data/:/data
      - ./dls/database:/home/app/database
      - ./dls/keras:/root/.keras
    